### ISSUE TITLE
Feature: Vocabulary Endpoints | Эндпоинты vocabulary

### ISSUE THREAD

**Issue by BU-Marina** [FSD-For-Self-Dev/LinguistaAPI#2]
# Vocabulary Endpoints

Feature: Vocabulary Endpoints | Ручки словаря

## Description

This Feature will add all actions for vocabulary page wherein the user can view his words and phrases, sort, filter them and searching
Реализовать все действия со словарем для страницы словаря, на которой пользователь может увидеть все слова/фразы в своем словаре, разделенные на "неактивные", "активные", "усвоенные", фильтровать, сортировать и искать по ним

![image](https://github.com/FSD-For-Self-Dev/LinguistaAPI/assets/77714654/6af181aa-1fa2-464c-bd59-b5bfc0043974)

## List of Tasks

- [x] [#7] Просмотр списка слов с пагинацией, поиском, сортировкой
- [x] [#8] Добавление, просмотр, удаление слова
- [x] [#9] Фильтрация списка слов
- [ ] [#10] Множественное добавление слов
- [ ] [#11] Редактирование слова
- [ ] [#13] Добавить в/удалить из избранного, получить список всех избранных слов, добавить в избранное несколько слов сразу
- [x] [#12] Получить случайное слово из словаря
- [x] [#14] Просмотр списка переводов слова, добавление перевода к слову, редактирование перевода, удаление
- [x] [#15] Просмотр списка примеров слова, добавление примера к слову, редактирование примера, удаление
- [x] [#16] Просмотр списка определений слова, добавление определения к слову, редактирование определения, удаление
- [ ] [#17] Просмотр списка ассоциаций слова, добавление ассоциации к слову, редактирование ассоциации, удаление
- [x] [#23] Добавление в/удаление из проблемных
