### ISSUE TITLE
Task: Vocabulary actions

### ISSUE THREAD

**Issue by BU-Marina** [FSD-For-Self-Dev/LinguistaAPI#5]
# Task Title

Task: Add vocabulary actions

## Task Description

This Task will add vocabulary actions

## Epic Parent

[Feature: Vocabulary](https://github.com/FSD-For-Self-Dev/LinguistaAPI/issues/2)

## Checklist

- [ ] [Words list with search, filtering, ordering, pagination]()
- [ ] [Words creation]()
- [ ] [Words multiple creation]()
- [ ] [Words retrieving]()
- [ ] [Adding translations/examples/definitions]()
- [ ]  [Words deletion]()
- [ ]  [Words edit]()
- [ ]  [Random word]()
